Ravenports generated: 21 Jun 2025 17:57

diff --git a/bucket_8E/elixir b/bucket_8E/elixir
--- a/bucket_8E/elixir
+++ b/bucket_8E/elixir
@@ -805,3 +805,17 @@ share/man/man1/
  iex.1
  mix.1
 
+
+[FILE:452:patches/patch-Makefile]
+--- Makefile.orig	2025-05-21 11:47:42 UTC
++++ Makefile
+@@ -28,7 +28,7 @@ SOURCE_DATE_EPOCH_FILE = $(SOURCE_DATE_E
+ 
+ define CHECK_ERLANG_RELEASE
+ 	erl -noshell -eval '{V,_} = string:to_integer(erlang:system_info(otp_release)), io:fwrite("~s", [is_integer(V) and (V >= 25)])' -s erlang halt | grep -q '^true'; \
+-		if [ $$? != 0 ]; then \
++		if [ 0 != 0 ]; then \
+ 		  echo "At least Erlang/OTP 25.0 is required to build Elixir"; \
+ 		  exit 1; \
+ 		fi
+
