Ravenports generated: 25 Jul 2023 19:43

diff --git a/bucket_0E/libvisual-plugins b/bucket_0E/libvisual-plugins
--- a/bucket_0E/libvisual-plugins
+++ b/bucket_0E/libvisual-plugins
@@ -39,6 +39,10 @@ FPC_EQUIVALENT=		graphics/libvisual04-plugins
 
 MUST_CONFIGURE=		gnu
 CONFIGURE_ARGS=		--disable-gstreamer-plugin
+			--disable-jack
+			--disable-portaudio
+			--disable-pulseaudio
+			--disable-alsa
 
 INSTALL_TARGET=		install-strip
 
@@ -337,4 +341,36 @@ share/libvisual-plugins-0.4/actor/actor_madspin/
 share/locale/de/LC_MESSAGES/libvisual-plugins-0.4.mo
 share/locale/es_AR/LC_MESSAGES/libvisual-plugins-0.4.mo
 share/locale/es_ES/LC_MESSAGES/libvisual-plugins-0.4.mo
+
+
+[FILE:1597:patches/patch-configure]
+--- configure.orig	2023-03-20 02:05:13 UTC
++++ configure
+@@ -20762,11 +20762,11 @@ fi
+   if test "$HAVE_GTK" = "yes"; then
+     build_actor_plugins="$build_actor_plugins gdkpixbuf"
+   else
+-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** GTK+ >= ${3.0} is not found.
++    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** GTK+ >= 3.0 is not found.
+ 	  	The libvisual GdkPixbuf image loader plugin won't be built.
+ 		GdkPixbuf is included within gtk+-3.0 and newer, which can be
+ 		downloaded at https://www.gtk.org/" >&5
+-printf "%s\n" "$as_me: WARNING: *** GTK+ >= ${3.0} is not found.
++printf "%s\n" "$as_me: WARNING: *** GTK+ >= 3.0 is not found.
+ 	  	The libvisual GdkPixbuf image loader plugin won't be built.
+ 		GdkPixbuf is included within gtk+-3.0 and newer, which can be
+ 		downloaded at https://www.gtk.org/" >&2;}
+@@ -20858,10 +20858,10 @@ fi
+   if test "$HAVE_GSTREAMER" = "yes"; then
+     build_actor_plugins="$build_actor_plugins gstreamer"
+   else
+-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** GStreamer >= ${1.0} is not found.
++    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** GStreamer >= 1.0 is not found.
+ 	  	The libvisual GStreamer viewer plugin won't be build.
+ 		GStreamer can be downloaded from https://gstreamer.freedesktop.org/" >&5
+-printf "%s\n" "$as_me: WARNING: *** GStreamer >= ${1.0} is not found.
++printf "%s\n" "$as_me: WARNING: *** GStreamer >= 1.0 is not found.
+ 	  	The libvisual GStreamer viewer plugin won't be build.
+ 		GStreamer can be downloaded from https://gstreamer.freedesktop.org/" >&2;}
+   fi
 
